/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
OscmidiModulatorAudioProcessorEditor::OscmidiModulatorAudioProcessorEditor (OscmidiModulatorAudioProcessor& p)
    : AudioProcessorEditor (&p),
      processor (p),
      m_eventQueue(0)
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (400, 300);

    m_receiveOSC.setEventQueue(m_eventQueue);
    processor.setEventQueue(m_eventQueue);

    // start osc thread
    m_receiveOSC.startThread();
}

OscmidiModulatorAudioProcessorEditor::~OscmidiModulatorAudioProcessorEditor()
{
}

//==============================================================================
void OscmidiModulatorAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);

}

void OscmidiModulatorAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..

}
