/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ReceiveOSC.h"
#include <queue>


//==============================================================================
/**
*/
class XyprocessorAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    XyprocessorAudioProcessorEditor (XyprocessorAudioProcessor* ownerFilter);
    ~XyprocessorAudioProcessorEditor();
    
    ReceiveOSC m_receiveOSC;
    
    std::queue<SensorEvent> m_eventQueue;
    
    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // PLUGINEDITOR_H_INCLUDED
