/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"

#include "ReceiveOSC.h"
#include "SensorEvent.h"


#include <queue>
#include <memory>


//==============================================================================
/**
*/
class OscmidiModulatorAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    OscmidiModulatorAudioProcessorEditor (OscmidiModulatorAudioProcessor&);
    ~OscmidiModulatorAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    OscmidiModulatorAudioProcessor& processor;

    ReceiveOSC m_receiveOSC;

    boost::lockfree::queue<SensorEvent> m_eventQueue;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (OscmidiModulatorAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
