/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
OscmidiModulatorAudioProcessorEditor::OscmidiModulatorAudioProcessorEditor (OscmidiModulatorAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p), fireUpOSC ("Fire Up OSC")
{
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (400, 300);
    
    // start osc thread
	receiveOSC.startThread();
}

OscmidiModulatorAudioProcessorEditor::~OscmidiModulatorAudioProcessorEditor()
{
}

//==============================================================================
void OscmidiModulatorAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);

    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World!", getLocalBounds(), Justification::centred, 1);
    
    addAndMakeVisible(&fireUpOSC);    
}

void OscmidiModulatorAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
    
    fireUpOSC.setBoundsRelative (0.05, 0.05, 0.90, 0.25);
}
